name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.0

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
